version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: MessengerDB
      POSTGRES_USER: messenger_user
      POSTGRES_PASSWORD: messenger_password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pgdata:
